/* tslint:disable */
/* eslint-disable */
/**
 * Goodsender API
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface Address {
    /**
     * Valid email address is required.
     */
    'email': string;
    /**
     * Optional display name
     */
    'name'?: string;
}
/**
 * Either inline_id or file_name is required. Content must be base64 encoded.
 */
export interface Attachment {
    /**
     * File name for the attachment
     */
    'file_name'?: string;
    /**
     * Base64 encoded content
     */
    'content'?: string;
    /**
     * MIME content type (required)
     */
    'content_type': string;
    /**
     * Inline attachment ID
     */
    'inline_id'?: string;
}
/**
 * @type ConsentEmailEntry
 * Single entry in the `emails` array of a consent request. Either a bare email string (back-compat) or a `{ email, name? }` object so callers can attach a display name to a specific recipient. 
 */
export type ConsentEmailEntry = ConsentEmailRecipient | string;

/**
 * Recipient envelope with optional display name. Pass this shape instead of a bare email string when you want the name to appear in the To header on the consent email and in subsequent listings.
 */
export interface ConsentEmailRecipient {
    /**
     * Recipient email address. Leading and trailing whitespace are stripped server-side.
     */
    'email': string;
    /**
     * Optional display name. Pass a non-empty string to set or replace the stored name. Passing `null`, an empty string, or omitting the field on a re-submitted recipient leaves any previously-stored name unchanged — clearing must be done via the dashboard / authenticated edit flow. 
     */
    'name'?: string | null;
}
export interface ConsentEmailRequest {
    /**
     * Domain for the email addresses.
     */
    'domain': string;
    /**
     * URL to which the user will be redirected after providing consent. {email} in the URL will be replaced with the recipient\'s email address.
     */
    'redirect_url'?: string;
    /**
     * Recipients to request consent from. Each entry may be either a plain email string or a `{ email, name? }` object so callers can attach a display name to a specific recipient. Mixing the two forms in one request is allowed. 
     */
    'emails': Array<ConsentEmailEntry>;
}
export interface ConsentEmailResult {
    'emails': Array<EmailAccount>;
}
export interface Domain {
    /**
     * The domain name.
     */
    'domain': string;
    /**
     * Subdomain used for click tracking.
     */
    'tracking': string;
    /**
     * Subdomain used for the return path.
     */
    'return_path': string;
    /**
     * Whether outbound mail from this domain must be sent over TLS.
     */
    'require_tls': boolean;
    'verification': DomainVerification;
}
export interface DomainListResponse {
    'domains': Array<Domain>;
    /**
     * Cursor to retrieve the next page of results. Omitted if there are no more results.
     */
    'nextCursor'?: string;
}
/**
 * Per-record verification state for the domain. `verified` is the overall flag; the individual `*_verified` fields indicate which DNS records still need attention when `verified` is `false`. 
 */
export interface DomainVerification {
    /**
     * Overall verification status. True only when every required DNS record is in place.
     */
    'verified': boolean;
    /**
     * Whether the tracking subdomain CNAME is in place.
     */
    'tracking_verified': boolean;
    /**
     * Whether the return-path subdomain CNAME is in place.
     */
    'return_path_verified': boolean;
    /**
     * Whether the first DKIM record is in place.
     */
    'dkim1_verified': boolean;
    /**
     * Whether the second DKIM record is in place.
     */
    'dkim2_verified': boolean;
}
export interface EmailAccount {
    /**
     * Recipient email address.
     */
    'email': string;
    /**
     * Optional display name for the recipient. Used in the To header on the consent email when present, and surfaced through the Dashboard. May be null when no name has been provided.
     */
    'name'?: string | null;
    /**
     * Domain part of the email address.
     */
    'domain': string;
    /**
     * Status of the recipient\'s consent for receiving emails. \'pending\' = awaiting consent email send, \'requested\' = consent email dispatched, \'failed\' = consent email delivery failed, \'granted\' = recipient consented to receive emails, \'denied\' = recipient declined to receive emails.
     */
    'consentStatus': EmailAccountConsentStatusEnum;
    /**
     * Status of the recipient\'s engagement with the emails.
     */
    'engagementStatus'?: EmailAccountEngagementStatusEnum;
}

export const EmailAccountConsentStatusEnum = {
    pending: 'pending',
    requested: 'requested',
    failed: 'failed',
    granted: 'granted',
    denied: 'denied',
} as const;

export type EmailAccountConsentStatusEnum = typeof EmailAccountConsentStatusEnum[keyof typeof EmailAccountConsentStatusEnum];
export const EmailAccountEngagementStatusEnum = {
    new: 'new',
    hot: 'hot',
    warm: 'warm',
    cooling: 'cooling',
    dormant: 'dormant',
    inactive: 'inactive',
} as const;

export type EmailAccountEngagementStatusEnum = typeof EmailAccountEngagementStatusEnum[keyof typeof EmailAccountEngagementStatusEnum];

export interface EmailListResponse {
    'emails': Array<EmailAccount>;
    /**
     * Cursor to retrieve the next page of results. Omitted if there are no more results.
     */
    'nextCursor'?: string;
}
export interface ErrorResponse {
    /**
     * Machine-readable error code.
     */
    'code': string;
    /**
     * Human-readable error message.
     */
    'message': string;
}
export interface QuotaExceededError {
    /**
     * Machine-readable error code.
     */
    'code': QuotaExceededErrorCodeEnum;
    /**
     * Whether the daily or monthly quota was exhausted.
     */
    'kind': QuotaExceededErrorKindEnum;
    /**
     * Human-readable error message.
     */
    'message': string;
    /**
     * Quota limit that was reached.
     */
    'limit': number;
    /**
     * Number of emails already used against the quota.
     */
    'used': number;
    /**
     * Timestamp at which the quota window resets.
     */
    'resetAt': string;
}

export const QuotaExceededErrorCodeEnum = {
    quota_exceeded: 'quota_exceeded',
} as const;

export type QuotaExceededErrorCodeEnum = typeof QuotaExceededErrorCodeEnum[keyof typeof QuotaExceededErrorCodeEnum];
export const QuotaExceededErrorKindEnum = {
    daily: 'daily',
    monthly: 'monthly',
} as const;

export type QuotaExceededErrorKindEnum = typeof QuotaExceededErrorKindEnum[keyof typeof QuotaExceededErrorKindEnum];

/**
 * Must provide valid sender and subject. At least one recipient (from \'to\', \'cc\', or \'bcc\') is required. Either \'text_content\', \'html_content\', \'markdown_content\', or \'template_id\' is required. When \'markdown_content\' is provided, \'text_content\' and \'html_content\' are ignored. 
 */
export interface SendEmail {
    /**
     * Sender address (required)
     */
    'from': Address;
    /**
     * To recipients. At least one recipient (to, cc, or bcc) is required. Maximum 1000 recipients per email.
     */
    'to': Array<Address>;
    /**
     * The subject of the email (required)
     */
    'subject': string;
    /**
     * Plain text content
     */
    'text_content'?: string;
    /**
     * HTML content
     */
    'html_content'?: string;
    /**
     * Markdown content. When provided, text_content and html_content are ignored. The raw markdown is used as text_content and rendered to HTML for html_content. 
     */
    'markdown_content'?: string;
    /**
     * Template ID for templated emails
     */
    'template_id'?: string;
    /**
     * Data to populate template variables
     */
    'template_data'?: { [key: string]: any; };
    /**
     * Email attachments
     */
    'attachments'?: Array<Attachment>;
    /**
     * Custom email headers
     */
    'headers'?: { [key: string]: string; };
    /**
     * Reply-to address
     */
    'reply_to'?: Address;
    /**
     * Unix timestamp for when to send the email. Must not be more than 72 hours in the future. If 0, sends immediately.
     */
    'send_time'?: number;
    /**
     * Custom data to include in webhook events. Maximum 10 keys, key length 50 chars, value length 100 chars.
     */
    'webhook_data'?: { [key: string]: string; };
    /**
     * Custom tag for tracking. Maximum 100 characters.
     */
    'tag'?: string;
    /**
     * Email tracking settings
     */
    'tracking'?: TrackingSettings;
}
export interface SendEmailErrorResponse {
    /**
     * Error message
     */
    'error': string;
}
export interface SendEmailRequest {
    /**
     * List of emails to send. Cannot be empty.
     */
    'emails': Array<SendEmail>;
}
export interface SendEmailResponse {
    /**
     * Number of emails sent (recipients had consent allowing delivery)
     */
    'sent': number;
    /**
     * Number of emails not sent because recipients did not have granted consent to receive emails
     */
    'declined': number;
}
export interface TemplateEmailRequest {
    /**
     * Sender address (required)
     */
    'from': Address;
    /**
     * Recipient address (required)
     */
    'to': Address;
    /**
     * The subject of the email (required)
     */
    'subject': string;
    'template': TemplateEmailRequestTemplate;
}
export interface TemplateEmailRequestTemplate {
    /**
     * The ID of the template to use
     */
    'template_id': string;
    /**
     * Key-value pairs to populate template variables
     */
    'variables'?: { [key: string]: string; };
}
export interface TemplateEmailResponse {
    /**
     * \"sent\" if the email was sent, \"declined\" if the recipient has opted out
     */
    'status': TemplateEmailResponseStatusEnum;
}

export const TemplateEmailResponseStatusEnum = {
    sent: 'sent',
    declined: 'declined',
} as const;

export type TemplateEmailResponseStatusEnum = typeof TemplateEmailResponseStatusEnum[keyof typeof TemplateEmailResponseStatusEnum];

/**
 * Controls email tracking and unsubscribe settings
 */
export interface TrackingSettings {
    /**
     * Whether to track email opens
     */
    'opens'?: boolean;
    /**
     * Whether to track link clicks
     */
    'clicks'?: boolean;
    /**
     * Whether to track unsubscribes
     */
    'unsubscribes'?: boolean;
    /**
     * Optional unsubscribe group ID. If not specified, uses global unsubscribe list. This setting is ignored if unsubscribes is false.
     */
    'unsubscribe_group_id'?: number | null;
}

/**
 * DomainsApi - axios parameter creator
 */
export const DomainsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain\'s verification state so callers can detect when DNS records still need attention. 
         * @summary List domains
         * @param {number} [limit] Maximum number of records to return.
         * @param {string} [cursor] Cursor for pagination, returned as &#x60;nextCursor&#x60; from a previous response.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDomains: async (limit?: number, cursor?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/domains`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DomainsApi - functional programming interface
 */
export const DomainsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DomainsApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain\'s verification state so callers can detect when DNS records still need attention. 
         * @summary List domains
         * @param {number} [limit] Maximum number of records to return.
         * @param {string} [cursor] Cursor for pagination, returned as &#x60;nextCursor&#x60; from a previous response.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDomains(limit?: number, cursor?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DomainListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDomains(limit, cursor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainsApi.listDomains']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DomainsApi - factory interface
 */
export const DomainsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DomainsApiFp(configuration)
    return {
        /**
         * Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain\'s verification state so callers can detect when DNS records still need attention. 
         * @summary List domains
         * @param {DomainsApiListDomainsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDomains(requestParameters: DomainsApiListDomainsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<DomainListResponse> {
            return localVarFp.listDomains(requestParameters.limit, requestParameters.cursor, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DomainsApi - interface
 */
export interface DomainsApiInterface {
    /**
     * Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain\'s verification state so callers can detect when DNS records still need attention. 
     * @summary List domains
     * @param {DomainsApiListDomainsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listDomains(requestParameters?: DomainsApiListDomainsRequest, options?: RawAxiosRequestConfig): AxiosPromise<DomainListResponse>;

}

/**
 * Request parameters for listDomains operation in DomainsApi.
 */
export interface DomainsApiListDomainsRequest {
    /**
     * Maximum number of records to return.
     */
    readonly limit?: number

    /**
     * Cursor for pagination, returned as &#x60;nextCursor&#x60; from a previous response.
     */
    readonly cursor?: string
}

/**
 * DomainsApi - object-oriented interface
 */
export class DomainsApi extends BaseAPI implements DomainsApiInterface {
    /**
     * Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain\'s verification state so callers can detect when DNS records still need attention. 
     * @summary List domains
     * @param {DomainsApiListDomainsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listDomains(requestParameters: DomainsApiListDomainsRequest = {}, options?: RawAxiosRequestConfig) {
        return DomainsApiFp(this.configuration).listDomains(requestParameters.limit, requestParameters.cursor, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * EmailsApi - axios parameter creator
 */
export const EmailsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve the current consent status for an email address. Optionally filter by sender domain.
         * @summary Get recipient consent status
         * @param {string} email Email address to look up.
         * @param {string} [domain] Optional sender domain to filter consent records by. When omitted, returns consent across all domains.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEmailConsentStatus: async (email: string, domain?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            assertParamExists('getEmailConsentStatus', 'email', email)
            const localVarPath = `/v1/emails/{email}`
                .replace(`{${"email"}}`, encodeURIComponent(String(email)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (domain !== undefined) {
                localVarQueryParameter['domain'] = domain;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a paginated list of email consent statuses for a domain.
         * @summary List email consent statuses
         * @param {string} domain Sender domain to filter consent records by.
         * @param {number} [limit] Maximum number of records to return.
         * @param {string} [cursor] Cursor for pagination.
         * @param {ListEmailConsentsConsentStatusEnum} [consentStatus] Status of the recipient\&#39;s consent for receiving emails. \&#39;pending\&#39; &#x3D; awaiting consent email send, \&#39;requested\&#39; &#x3D; consent email dispatched, \&#39;failed\&#39; &#x3D; consent email delivery failed, \&#39;granted\&#39; &#x3D; recipient consented to receive emails, \&#39;denied\&#39; &#x3D; recipient declined to receive emails.
         * @param {ListEmailConsentsEngagementStatusEnum} [engagementStatus] Status of the recipient\&#39;s engagement with the emails.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEmailConsents: async (domain: string, limit?: number, cursor?: string, consentStatus?: ListEmailConsentsConsentStatusEnum, engagementStatus?: ListEmailConsentsEngagementStatusEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('listEmailConsents', 'domain', domain)
            const localVarPath = `/v1/emails`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (domain !== undefined) {
                localVarQueryParameter['domain'] = domain;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (consentStatus !== undefined) {
                localVarQueryParameter['consentStatus'] = consentStatus;
            }

            if (engagementStatus !== undefined) {
                localVarQueryParameter['engagementStatus'] = engagementStatus;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
         * @summary Request recipients\' consent to receive emails from your domain
         * @param {ConsentEmailRequest} consentEmailRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestEmailConsent: async (consentEmailRequest: ConsentEmailRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'consentEmailRequest' is not null or undefined
            assertParamExists('requestEmailConsent', 'consentEmailRequest', consentEmailRequest)
            const localVarPath = `/v1/emails/consent`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(consentEmailRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient\'s consent state. 
         * @summary Send an email or a batch of emails
         * @param {SendEmailRequest} sendEmailRequest List of emails to send
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendEmail: async (sendEmailRequest: SendEmailRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sendEmailRequest' is not null or undefined
            assertParamExists('sendEmail', 'sendEmailRequest', sendEmailRequest)
            const localVarPath = `/v1/emails/send`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendEmailRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \"denied\" consent, the response returns `{\"status\": \"declined\"}` and the email is not sent. Unknown recipients are auto-registered with \"pending\" consent. The template endpoint does not change the recipient\'s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender\'s email address. 
         * @summary Send a transactional email using a template
         * @param {TemplateEmailRequest} templateEmailRequest Template email to send
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendTemplateEmail: async (templateEmailRequest: TemplateEmailRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'templateEmailRequest' is not null or undefined
            assertParamExists('sendTemplateEmail', 'templateEmailRequest', templateEmailRequest)
            const localVarPath = `/v1/emails/template`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(templateEmailRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmailsApi - functional programming interface
 */
export const EmailsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmailsApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve the current consent status for an email address. Optionally filter by sender domain.
         * @summary Get recipient consent status
         * @param {string} email Email address to look up.
         * @param {string} [domain] Optional sender domain to filter consent records by. When omitted, returns consent across all domains.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEmailConsentStatus(email: string, domain?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EmailAccount>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEmailConsentStatus(email, domain, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmailsApi.getEmailConsentStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve a paginated list of email consent statuses for a domain.
         * @summary List email consent statuses
         * @param {string} domain Sender domain to filter consent records by.
         * @param {number} [limit] Maximum number of records to return.
         * @param {string} [cursor] Cursor for pagination.
         * @param {ListEmailConsentsConsentStatusEnum} [consentStatus] Status of the recipient\&#39;s consent for receiving emails. \&#39;pending\&#39; &#x3D; awaiting consent email send, \&#39;requested\&#39; &#x3D; consent email dispatched, \&#39;failed\&#39; &#x3D; consent email delivery failed, \&#39;granted\&#39; &#x3D; recipient consented to receive emails, \&#39;denied\&#39; &#x3D; recipient declined to receive emails.
         * @param {ListEmailConsentsEngagementStatusEnum} [engagementStatus] Status of the recipient\&#39;s engagement with the emails.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listEmailConsents(domain: string, limit?: number, cursor?: string, consentStatus?: ListEmailConsentsConsentStatusEnum, engagementStatus?: ListEmailConsentsEngagementStatusEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmailListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listEmailConsents(domain, limit, cursor, consentStatus, engagementStatus, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmailsApi.listEmailConsents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
         * @summary Request recipients\' consent to receive emails from your domain
         * @param {ConsentEmailRequest} consentEmailRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestEmailConsent(consentEmailRequest: ConsentEmailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsentEmailResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestEmailConsent(consentEmailRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmailsApi.requestEmailConsent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient\'s consent state. 
         * @summary Send an email or a batch of emails
         * @param {SendEmailRequest} sendEmailRequest List of emails to send
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendEmail(sendEmailRequest: SendEmailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SendEmailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendEmail(sendEmailRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmailsApi.sendEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \"denied\" consent, the response returns `{\"status\": \"declined\"}` and the email is not sent. Unknown recipients are auto-registered with \"pending\" consent. The template endpoint does not change the recipient\'s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender\'s email address. 
         * @summary Send a transactional email using a template
         * @param {TemplateEmailRequest} templateEmailRequest Template email to send
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendTemplateEmail(templateEmailRequest: TemplateEmailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TemplateEmailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendTemplateEmail(templateEmailRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmailsApi.sendTemplateEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EmailsApi - factory interface
 */
export const EmailsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmailsApiFp(configuration)
    return {
        /**
         * Retrieve the current consent status for an email address. Optionally filter by sender domain.
         * @summary Get recipient consent status
         * @param {EmailsApiGetEmailConsentStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEmailConsentStatus(requestParameters: EmailsApiGetEmailConsentStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<EmailAccount>> {
            return localVarFp.getEmailConsentStatus(requestParameters.email, requestParameters.domain, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a paginated list of email consent statuses for a domain.
         * @summary List email consent statuses
         * @param {EmailsApiListEmailConsentsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEmailConsents(requestParameters: EmailsApiListEmailConsentsRequest, options?: RawAxiosRequestConfig): AxiosPromise<EmailListResponse> {
            return localVarFp.listEmailConsents(requestParameters.domain, requestParameters.limit, requestParameters.cursor, requestParameters.consentStatus, requestParameters.engagementStatus, options).then((request) => request(axios, basePath));
        },
        /**
         * Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
         * @summary Request recipients\' consent to receive emails from your domain
         * @param {EmailsApiRequestEmailConsentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestEmailConsent(requestParameters: EmailsApiRequestEmailConsentRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsentEmailResult> {
            return localVarFp.requestEmailConsent(requestParameters.consentEmailRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient\'s consent state. 
         * @summary Send an email or a batch of emails
         * @param {EmailsApiSendEmailRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendEmail(requestParameters: EmailsApiSendEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<SendEmailResponse> {
            return localVarFp.sendEmail(requestParameters.sendEmailRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \"denied\" consent, the response returns `{\"status\": \"declined\"}` and the email is not sent. Unknown recipients are auto-registered with \"pending\" consent. The template endpoint does not change the recipient\'s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender\'s email address. 
         * @summary Send a transactional email using a template
         * @param {EmailsApiSendTemplateEmailRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendTemplateEmail(requestParameters: EmailsApiSendTemplateEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<TemplateEmailResponse> {
            return localVarFp.sendTemplateEmail(requestParameters.templateEmailRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EmailsApi - interface
 */
export interface EmailsApiInterface {
    /**
     * Retrieve the current consent status for an email address. Optionally filter by sender domain.
     * @summary Get recipient consent status
     * @param {EmailsApiGetEmailConsentStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getEmailConsentStatus(requestParameters: EmailsApiGetEmailConsentStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<EmailAccount>>;

    /**
     * Retrieve a paginated list of email consent statuses for a domain.
     * @summary List email consent statuses
     * @param {EmailsApiListEmailConsentsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listEmailConsents(requestParameters: EmailsApiListEmailConsentsRequest, options?: RawAxiosRequestConfig): AxiosPromise<EmailListResponse>;

    /**
     * Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
     * @summary Request recipients\' consent to receive emails from your domain
     * @param {EmailsApiRequestEmailConsentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    requestEmailConsent(requestParameters: EmailsApiRequestEmailConsentRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsentEmailResult>;

    /**
     * Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient\'s consent state. 
     * @summary Send an email or a batch of emails
     * @param {EmailsApiSendEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sendEmail(requestParameters: EmailsApiSendEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<SendEmailResponse>;

    /**
     * Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \"denied\" consent, the response returns `{\"status\": \"declined\"}` and the email is not sent. Unknown recipients are auto-registered with \"pending\" consent. The template endpoint does not change the recipient\'s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender\'s email address. 
     * @summary Send a transactional email using a template
     * @param {EmailsApiSendTemplateEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sendTemplateEmail(requestParameters: EmailsApiSendTemplateEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<TemplateEmailResponse>;

}

/**
 * Request parameters for getEmailConsentStatus operation in EmailsApi.
 */
export interface EmailsApiGetEmailConsentStatusRequest {
    /**
     * Email address to look up.
     */
    readonly email: string

    /**
     * Optional sender domain to filter consent records by. When omitted, returns consent across all domains.
     */
    readonly domain?: string
}

/**
 * Request parameters for listEmailConsents operation in EmailsApi.
 */
export interface EmailsApiListEmailConsentsRequest {
    /**
     * Sender domain to filter consent records by.
     */
    readonly domain: string

    /**
     * Maximum number of records to return.
     */
    readonly limit?: number

    /**
     * Cursor for pagination.
     */
    readonly cursor?: string

    /**
     * Status of the recipient\&#39;s consent for receiving emails. \&#39;pending\&#39; &#x3D; awaiting consent email send, \&#39;requested\&#39; &#x3D; consent email dispatched, \&#39;failed\&#39; &#x3D; consent email delivery failed, \&#39;granted\&#39; &#x3D; recipient consented to receive emails, \&#39;denied\&#39; &#x3D; recipient declined to receive emails.
     */
    readonly consentStatus?: ListEmailConsentsConsentStatusEnum

    /**
     * Status of the recipient\&#39;s engagement with the emails.
     */
    readonly engagementStatus?: ListEmailConsentsEngagementStatusEnum
}

/**
 * Request parameters for requestEmailConsent operation in EmailsApi.
 */
export interface EmailsApiRequestEmailConsentRequest {
    readonly consentEmailRequest: ConsentEmailRequest
}

/**
 * Request parameters for sendEmail operation in EmailsApi.
 */
export interface EmailsApiSendEmailRequest {
    /**
     * List of emails to send
     */
    readonly sendEmailRequest: SendEmailRequest
}

/**
 * Request parameters for sendTemplateEmail operation in EmailsApi.
 */
export interface EmailsApiSendTemplateEmailRequest {
    /**
     * Template email to send
     */
    readonly templateEmailRequest: TemplateEmailRequest
}

/**
 * EmailsApi - object-oriented interface
 */
export class EmailsApi extends BaseAPI implements EmailsApiInterface {
    /**
     * Retrieve the current consent status for an email address. Optionally filter by sender domain.
     * @summary Get recipient consent status
     * @param {EmailsApiGetEmailConsentStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEmailConsentStatus(requestParameters: EmailsApiGetEmailConsentStatusRequest, options?: RawAxiosRequestConfig) {
        return EmailsApiFp(this.configuration).getEmailConsentStatus(requestParameters.email, requestParameters.domain, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a paginated list of email consent statuses for a domain.
     * @summary List email consent statuses
     * @param {EmailsApiListEmailConsentsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listEmailConsents(requestParameters: EmailsApiListEmailConsentsRequest, options?: RawAxiosRequestConfig) {
        return EmailsApiFp(this.configuration).listEmailConsents(requestParameters.domain, requestParameters.limit, requestParameters.cursor, requestParameters.consentStatus, requestParameters.engagementStatus, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
     * @summary Request recipients\' consent to receive emails from your domain
     * @param {EmailsApiRequestEmailConsentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public requestEmailConsent(requestParameters: EmailsApiRequestEmailConsentRequest, options?: RawAxiosRequestConfig) {
        return EmailsApiFp(this.configuration).requestEmailConsent(requestParameters.consentEmailRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient\'s consent state. 
     * @summary Send an email or a batch of emails
     * @param {EmailsApiSendEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sendEmail(requestParameters: EmailsApiSendEmailRequest, options?: RawAxiosRequestConfig) {
        return EmailsApiFp(this.configuration).sendEmail(requestParameters.sendEmailRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \"denied\" consent, the response returns `{\"status\": \"declined\"}` and the email is not sent. Unknown recipients are auto-registered with \"pending\" consent. The template endpoint does not change the recipient\'s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender\'s email address. 
     * @summary Send a transactional email using a template
     * @param {EmailsApiSendTemplateEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sendTemplateEmail(requestParameters: EmailsApiSendTemplateEmailRequest, options?: RawAxiosRequestConfig) {
        return EmailsApiFp(this.configuration).sendTemplateEmail(requestParameters.templateEmailRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ListEmailConsentsConsentStatusEnum = {
    pending: 'pending',
    requested: 'requested',
    failed: 'failed',
    granted: 'granted',
    denied: 'denied',
} as const;
export type ListEmailConsentsConsentStatusEnum = typeof ListEmailConsentsConsentStatusEnum[keyof typeof ListEmailConsentsConsentStatusEnum];
export const ListEmailConsentsEngagementStatusEnum = {
    new: 'new',
    hot: 'hot',
    warm: 'warm',
    cooling: 'cooling',
    dormant: 'dormant',
    inactive: 'inactive',
} as const;
export type ListEmailConsentsEngagementStatusEnum = typeof ListEmailConsentsEngagementStatusEnum[keyof typeof ListEmailConsentsEngagementStatusEnum];


